services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Fresh\DoctrineEnumBundle\Twig\Extension\:
        resource: '../../Twig/Extension/'
        arguments:
            $registeredTypes: "%doctrine.dbal.connection_factory.types%"
        tags:
            - 'twig.extension'

    Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser:
        class: Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser
        arguments:
            $registeredTypes: "%doctrine.dbal.connection_factory.types%"
        tags:
            - 'form.type_guesser'
