language: php
sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

allow_failures:
  - php: hhvm

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

#Symfony 3.0 requires PHP 5.5
matrix:
  exclude:
    - php: 5.4
      env: SYMFONY_VERSION=3.0.*

before_install:
  - composer self-update
  - composer require --no-update symfony/symfony "$SYMFONY_VERSION"

install:
    - composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --ignore=vendor --ignore=Tests --standard=./vendor/escapestudios/symfony2-coding-standard/Symfony2
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - genvaldartem@gmail.com
