language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer install --dev
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=PSR2 --ignore=/vendor ./
  - phpunit --coverage-clover=coverage.xml  
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - genvaldartem@gmail.com
