language: php

php:
  - 5.3

before_install:
  - sudo pip install codecov

before_script:
  - composer install --dev
  - pear install --alldeps PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --standard=PSR2 --ignore=/vendor ./
  - phpunit --coverage-clover=coverage.xml

after_success:
  - codecov

notifications:
  email:
    - genvaldartem@gmail.com
